import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <nav style={{width : "100%", display: "flex", background: "gray", justifyContent: "center", fontSize: "40px", alignContent: "space-between"}}>
          <Link href="/" style={{backgroundColor: "blue"}} >Home</Link>
          <Link href="/posts" style={{backgroundColor: "burlywood"}}>Posts</Link>
          <Link href="/articles" style={{backgroundColor: "blueviolet"}}>Articles</Link>
        </nav>



        {children}
      </body>
    </html>
  );
}
